### ISSUE TITLE
Weird error message for invalid config file

### ISSUE THREAD

**Issue by juliandescottes** [captainbrosset/packman#1]
Hi,

With the following configuration : 

``` yaml
source: D:/Documents/Dropbox/sandbox/games
destination: target
visitors:
    - sep
    - uglify
packages:
    main.js:
        files:
            - EventBus.js
```

Packman  logs a misleading error message : [ERR] Could not find configuration file packman.yaml
Where actually the issue is with the 'uglify' visitor which doesn't exist.
