### ISSUE TITLE
Infinite loop when a certain number of visitors are there

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/packman#5]
Not clear yet what's causing the issue ... 

``` YAML
source: build/target/atloader
destination: build/target/standard
eraseIfExists: true
urlmap: ./build/config/standardmap.json
visitors:
- uglify
- "./build/config/visitors/atmapreader.js"
- "./build/config/visitors/atmultipart.js"
- "./build/config/visitors/license.js"
packages:
    aria/ariatemplates.js:
        files:
        - aria/atloader.js
        visitors:
        - "./build/config/visitors/atmapwriter.js"
```
